services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app/server
    ports:
      - "1323:1323"
    restart: always
    tty: true
    environment:
      ENV: "development"
      PORT: "1323"     
    command: ["make", "run"]

