package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"server/graphql/generated/model"
)

// PostMessage is the resolver for the postMessage field.
func (r *mutationResolver) PostMessage(ctx context.Context, input model.MessageInput) (*model.Message, error) {
	r.Mutex.Lock()
	defer r.Mutex.Unlock()
	for _, ch := range r.MessageID[int64(input.ChatID)] {
		ch <- &model.Message{
			ChatID: input.ChatID,
			Text:   input.Text,
		}
	}
	const postStatus = "sent"
	return &model.Message{
		ChatID: input.ChatID,
		Text:   input.Text,
		Type:   postStatus,
	}, nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context) ([]*model.Message, error) {
	return []*model.Message{
		{
			ChatID: 1,
			Text:   "Hello World",
		},
	}, nil
}

// MessagePosted is the resolver for the messagePosted field.
func (r *subscriptionResolver) MessagePosted(ctx context.Context, chatID int64) (<-chan *model.Message, error) {
	r.Mutex.Lock()
	defer r.Mutex.Unlock()

	ch := make(chan *model.Message, 1)
	r.MessageID[chatID] = append(r.MessageID[chatID], ch)

	go func() {
		<-ctx.Done()
		r.Mutex.Lock()
		defer r.Mutex.Unlock()
		for i, c := range r.MessageID[chatID] {
			if c == ch {
				r.MessageID[chatID] = append(r.MessageID[chatID][:i], r.MessageID[chatID][i+1:]...)
				break
			}
		}
	}()

	return ch, nil
}
